#!/usr/bin/env php
<?php

include $_composer_autoload_path ?? __DIR__ . '/vendor/autoload.php';

$application = new \Symfony\Component\Console\Application();
$application->add(new \PhpStats\Commands\Stats());
$application->run();
