#!/usr/bin/env php
<?php

include $_composer_autoload_path ?? __DIR__ . '/vendor/autoload.php';

$application = new \Symfony\Component\Console\Application();
$command = new \PhpStats\Commands\Stats();
$application->add($command);
$application->setDefaultCommand($command->getName(), true);
$application->run();
